export const data = {
    items: [
        {
            id: 1,
            name: 'Arts on Creck',
            slug: 'arts-on-creck',
            type: 'Painting',
            image: '/topaz.png',
            price: 1500,
            unsoldAmt: 10,
            totalAmt: 10,
            artist: 'Jake Noah',
            description: 'Lovely art',
        },
        {
            id: 2,
            name: 'Acting The Boys',
            slug: 'arts-on-creck',
            type: 'Painting',
            image: '/logo.png',
            price: 200,
            unsoldAmt: 10,
            totalAmt: 10,
            artist: 'Jake Flow',
            description: 'Lovely art',
        },
        {
            id: 3,
            name: 'Art22',
            slug: 'arts-on-creck',
            type: 'Painting',
            image: '/logo.png',
            price: 1970,
            unsoldAmt: 10,
            totalAmt: 10,
            artist: 'Covey Noah',
            description: 'Lovely art',
        },
        {
            id: 4,
            name: 'GML Sol',
            slug: 'arts-on-creck',
            type: 'Painting',
            image: '/topaz.png',
            price: 500,
            unsoldAmt: 10,
            totalAmt: 10,
            artist: 'Jake Noah',
            description: 'Lovely art',
        },
        {
            id: 5,
            name: 'Awesome',
            slug: 'arts-on-creck',
            type: 'Painting',
            image: '/logo.png',
            price: 12500,
            unsoldAmt: 10,
            totalAmt: 10,
            artist: 'Jake Noah',
            description: 'Lovely art',
        },
        {
            id: 6,
            name: 'Arts consumania',
            slug: 'arts-on-creck',
            type: 'Painting',
            image: '/logo.png',
            price: 100,
            unsoldAmt: 10,
            totalAmt: 10,
            artist: 'James Sparrow',
            description: 'Lovely art',
        },
        {
            id: 7,
            name: 'Artistic proof',
            slug: 'arts-on-creck',
            type: 'Painting',
            image: '/topaz.png',
            price: 1800,
            unsoldAmt: 10,
            totalAmt: 10,
            artist: 'Jake S.',
            description: 'Lovely art',
        },
        {
            id: 8,
            name: 'Global warming',
            slug: 'arts-on-creck',
            type: 'Painting',
            image: '/logo.png',
            price: 700,
            unsoldAmt: 10,
            totalAmt: 10,
            artist: 'Olu Swipe',
            description: 'Lovely art',
        }
    ]
}